<?xml version="1.0"?>
<robot name="my_robot" xmlns:xacro="https://www.ros.org/wiki/xacro" >


    <xacro:include filename="common_properties.xacro" />
	<xacro:include filename="navcon_control.xacro" />
	
    <xacro:include filename="camera.xacro" />
    <xacro:include filename="laser.xacro" />


    <xacro:property name="base_length" value="0.6" /> 
    <xacro:property name="base_width" value="0.4" />
    <xacro:property name="base_height" value="0.2" />
    <xacro:property name="wheel_radius" value="0.1" />
    <xacro:property name="wheel_length" value="0.07" />

    <link name="base_footprint" />

    <link name="base_link">
        <visual>
            <geometry>
                <box size="${base_length} ${base_width} ${base_height}" />
            </geometry>
            <origin xyz="0 0 ${base_height / 2.0}" rpy="0 0 0" />
            <material name="white" />
        </visual>
        <collision>    
            <geometry>
                <box size="${base_length} ${base_width} ${base_height}" />
            </geometry>
            <origin xyz="0 0 ${base_height / 2.0}" rpy="0 0 0" />
        </collision>
        <xacro:box_inertia m="5.0" l="${2*base_length}" w="${2*base_width}" h="${2*base_height}"
                           xyz="0 0 ${base_height / 2.0}" rpy="0 0 0" />
    </link>
    <xacro:macro name="wheel_link" params="prefix">
        <link name="${prefix}_wheel_link">
            <visual>
                <geometry>
                    <cylinder radius="${wheel_radius}" length="${wheel_length}" />
                </geometry>
                <origin xyz="0 0 0" rpy="${pi / 2.0} 0 0" />
                <material name="grey" />
            </visual>
            <collision>
                <geometry>
                    <cylinder radius="${wheel_radius}" length="${wheel_length}" />
                </geometry>
                <origin xyz="0 0 0" rpy="${pi / 2.0} 0 0" />
            </collision>
            <xacro:cylinder_inertia m="1.0" r="${2*wheel_radius}" h="${2*wheel_length}"
                                    xyz="0 0 0" rpy="${pi / 2.0} 0 0" />   
        </link>

    </xacro:macro>

    <xacro:wheel_link prefix="str1_front_left"/>
    <xacro:wheel_link prefix="str2_front_right"/>
    <xacro:wheel_link prefix="right_front" />
    <xacro:wheel_link prefix="left_front" />
    <xacro:wheel_link prefix="right_back" />
    <xacro:wheel_link prefix="left_back" />

    <joint name="base_joint" type="fixed">
        <parent link="base_footprint" />
        <child link="base_link" />
        <origin xyz="0 0 0" rpy="0 0 0" />
    </joint> 

    <joint name="base_right_back_wheel_joint" type="continuous">
        <parent link="base_link" />
        <child link="right_back_wheel_link" />
        <origin xyz="${-base_length / 4.0} ${-(base_width + wheel_length) / 2.0} 0" rpy="0 0 0" />
        <limit  effort="10" velocity="5000"/>
        <axis xyz="0 1 0" />
    </joint> 

    <joint name="base_left_back_wheel_joint" type="continuous">
        <parent link="base_link" />
        <child link="left_back_wheel_link" />
        <origin xyz="${-base_length / 4.0} ${(base_width + wheel_length) / 2.0} 0" rpy="0 0 0" />
        <limit  effort="10" velocity="5000"/>
        <axis xyz="0 1 0" />
    </joint>

    <joint name="base_right_front_wheel_joint" type="continuous">
        <parent link="str2_front_right_wheel_link" />
        <child link="right_front_wheel_link" />
        <origin xyz="0 0 0" rpy="0 0 0" />
        <limit  effort="10" velocity="5000"/>
        <axis xyz="0 1 0" />
    </joint>

    <joint name="base_left_front_wheel_joint" type="continuous">
        <parent link="str1_front_left_wheel_link" />
        <child link="left_front_wheel_link" />
        <origin xyz="0 0 0" rpy="0 0 0" />
		<limit  effort="10" velocity="5000"/>
        <axis xyz="0 1 0" />
    </joint>

    <joint name="base_str1_front_left_joint" type="revolute">
		<limit lower="-0.30" upper="0.30" effort="100" velocity="100"/>
        <parent link="base_link" />
        <child link="str1_front_left_wheel_link" />
        <origin xyz="${base_length / 4.0} ${(base_width + wheel_length) / 2.0} 0" rpy="0 0 0" />
        <axis xyz="0 0 1" />

    </joint>

    <joint name="base_str2_front_right_joint" type="revolute">
        <parent link="base_link" />
		<limit lower="-0.30" upper="0.30" effort="100" velocity="100"/>
        <child link="str2_front_right_wheel_link" />
        <origin xyz="${base_length / 4.0} ${-(base_width + wheel_length) / 2.0} 0" rpy="0 0 0" />
        <axis xyz="0 0 1" />
    </joint>

	<link name="imu_link">
		<visual>
		  <geometry>
			<box size="0.1 0.1 0.1"/>
		  </geometry>
		</visual>
	
		<collision>
		  <geometry>
			<box size="0.1 0.1 0.1"/>
		  </geometry>
		</collision>
	
		<xacro:box_inertia m="0.1" w="0.1" l="0.1" h="0.1" xyz="0 0 0" rpy="0 0 0"/>
	  </link>
	
	  <joint name="imu_joint" type="fixed">
		<parent link="base_link"/>
		<child link="imu_link"/>
		<origin xyz="0 0 0.01"/>
	  </joint>
	
	  <gazebo reference="imu_link">
		<sensor name="imu_sensor" type="imu">
		  <plugin filename="libgazebo_ros_imu_sensor.so" name="imu_plugin">
			<ros>
			  <namespace>/demo</namespace>
			  <remapping>~/out:=imu</remapping>
			</ros>
			<initial_orientation_as_reference>false</initial_orientation_as_reference>
		  </plugin>
		  <always_on>true</always_on>
		  <update_rate>100</update_rate>
		  <visualize>true</visualize>
		  <imu>
			<angular_velocity>
			  <x>
				<noise type="gaussian">
				  <mean>0.0</mean>
				  <stddev>2e-4</stddev>
				  <bias_mean>0.0000075</bias_mean>
				  <bias_stddev>0.0000008</bias_stddev>
				</noise>
			  </x>
			  <y>
				<noise type="gaussian">
				  <mean>0.0</mean>
				  <stddev>2e-4</stddev>
				  <bias_mean>0.0000075</bias_mean>
				  <bias_stddev>0.0000008</bias_stddev>
				</noise>
			  </y>
			  <z>
				<noise type="gaussian">
				  <mean>0.0</mean>
				  <stddev>2e-4</stddev>
				  <bias_mean>0.0000075</bias_mean>
				  <bias_stddev>0.0000008</bias_stddev>
				</noise>
			  </z>
			</angular_velocity>
			<linear_acceleration>
			  <x>
				<noise type="gaussian">
				  <mean>0.0</mean>
				  <stddev>1.7e-2</stddev>
				  <bias_mean>0.1</bias_mean>
				  <bias_stddev>0.001</bias_stddev>
				</noise>
			  </x>
			  <y>
				<noise type="gaussian">
				  <mean>0.0</mean>
				  <stddev>1.7e-2</stddev>
				  <bias_mean>0.1</bias_mean>
				  <bias_stddev>0.001</bias_stddev>
				</noise>
			  </y>
			  <z>
				<noise type="gaussian">
				  <mean>0.0</mean>
				  <stddev>1.7e-2</stddev>
				  <bias_mean>0.1</bias_mean>
				  <bias_stddev>0.001</bias_stddev>
				</noise>
			  </z>
			</linear_acceleration>
		  </imu>
		</sensor>
	  </gazebo> 
	
</robot>